<?php


namespace app\admin\controller;


use think\Controller;
use think\Db;

class Category extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }

    public function add(){
        if (!$this->request->isPost()){
            return json([
               'code'=>'404',
               'msg'=>'请求方式错误'
            ]);
        }

        $data=$this->request->post();
        $validate=validate('Category');
        if (!$validate->scene('add')->check($data)){
            return json([
                'code'=>404,
                'msg'=>$validate->getError()
            ]);
        }
       $result=Db::table('category')->insert($data);
        if($result){
            return json([
                'code'=>200,
                'msg'=>'分类添加成功'
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'分类添加失败'
            ]);

        }

    }




    /*
     * 查看数据 分页 搜索
     *
     * limit page
     * */

    public function index(){
        $data=$this->request->get();
        if (isset($data['page']) && !empty($data['page'])){
            $page=$data['page'];
        }else{
            $page=1;
        }

        if (isset($data['limit']) && !empty($data['limit'])){
            $limit=$data['limit'];
        }else{
            $limit=5;
        }

        $where=[];

        if (isset($data['cname']) && !empty($data['cname'])){
            $where['cname']=['like','%'.$data['cname'].'%'];
        }

        $category=Db::table('category')->field('cid,cname,cdesc')->where($where)->page($page)->limit($limit)->select();
        $count = Db::table('category')->where($where)->count();

        if($category && $count){
            return json([
                'code'=>200,
                'msg'=>'数据获取成功',
                'data'=>$category,
                'total'=>$count
        ]);
        }else{
            return json([
                'code'=>200,
                'msg'=>'暂无数据',
            ]);
        }

    }

    public function read(){
        $data = $this->request->get();
        $validate=validate('Category');
        if (!$validate->scene('read')->check($data)){
            return json([
                'code'=>404,
                'msg'=>$validate->getError()
            ]);

        }
        $category=Db::table('category')->where('cid',$data['cid'])->find();
        if($category){
            return json([
                'code'=>200,
                'msg'=>'数据读取成功',
                'data'=>$category

            ]);
        }else{
            return json([
                'code'=>200,
                'msg'=>'暂无数据'
            ]);

        }

    }
    function changePassword(){
        $uid=$this->request->id;
    }

}