<?php

namespace app\admin\controller;

use think\Controller;
use think\Db;
use think\Request;

class Stayhome extends Controller
{
    public $code;
    public $validate;
    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->code=config('code');
        $this->validate=validate('Stayhome');
    }

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $this->code['success'];
        return 'index';
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        $data=$this->request->get();

        if (isset($data['page'])&&!empty($data['page'])){
            $page=$data['page'];
        }else{
            $page=1;
        }

        if (isset($data['limit'])&&!empty($data['limit'])){
            $limit=$data['limit'];
        }else{
            $limit=10;
        }
        $where=[];
        if (isset($data['scity'])&&!empty($data['scity']))
        //
        return 'create';
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
        $data=$this->request->post();
//        $this->validate->scene()->check();
        $sname=$data['sname'];
        $data['ctime']=time();
        Db::table('stayhome')->where('sname',$sname)-count();
//        if ($isExist){
//
//        }

        $result=Db::table('stayhome')->insert($data);
        if ($result){
            return json([
                'code'=>$this->code['success'],
                'msg'=>'数据添加成功'

            ]);
        }else{
            return json([
                'code'=>$this->code['fail'],
                'msg'=>'数据添加成功'
            ]);
        }
        config('code.success');
        validate('Stayhome');

//        $result=Db::table()
        config('code.success');
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        validate('Stayhome');

        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
